apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testpay
  namespace: testpay
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts: [api.testpay.dev]
      secretName: testpay-tls
  rules:
    - host: api.testpay.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: testpay
                port: { number: 80 }
